name: Deploy

run-name: CI/CD

on: 
    workflow_dispatch:
    push:
        branches: [ "main" ]

jobs:   
  publish:
    environment: test-task-prod
    env:
      BACKEND_DOMAIN: http://${{ secrets.HOST }}
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}

    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
            name: Build and push
            run: |
              docker compose build
              docker compose push 

  deploy:
    environment: test-task-prod
    needs: publish
    runs-on: ubuntu-latest
    steps:
        - name: install ssh keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts

        - name: connect and pull
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} "cd ${{ secrets.DIRECTORY }} && docker compose pull && docker compose up -d && docker image prune -f && exit"
        - name: cleanup
          run: rm -rf ~/.ssh
